### ISSUE TITLE
parsing of position_lat and position_long

### ISSUE THREAD

**Issue by MichielBbal** [dtcooper/python-fitparse#102]
When I use the script under 'Usage Examples' provided on http://dtcooper.github.io/python-fitparse/ the position_long and position_lat are wrong.

**Comment by flynn-d** [comment]
Maybe you had the same issue as I did, in scratching my head about what units the lat and long are in. They are in semicircles, see https://github.com/dtcooper/python-fitparse/issues/43 and also the `.fields` method as below:

```
file_obj = open(path_to_.fit_file, 'rb')
fitfile = FitFile(file_obj)
DataMessage = fitfile.messages
DataMessage[value_for_a_record].fields
```

**Comment by MichielBbal** [comment]
Many thanks, flynn-d! 
That was exactly what I needed.

**Comment by MichielBbal** [comment]
With your help I was able to complete a jupyter notebook on plotting the fit file on a map.
Please find it [here](https://github.com/MichielBbal/cycling_data).

Many thanks again!
