### ISSUE TITLE
Invalid field size

### ISSUE THREAD

**Issue by jdwil** [dtcooper/python-fitparse#111]
I'm hitting the following exception quite a bit lately:

https://github.com/dtcooper/python-fitparse/blob/5a02aef50dbb7450ed7d00f82594bab18d00581a/fitparse/base.py#L193

The Java tools in the FIT sdk can parse these files fine. Can anyone elaborate on the comment above the exception and/or point me in the right direction?

**Comment by jdwil** [comment]
Oh, I get it... use the Byte type as a fallback. This actually seems to work:

```            
if (field_size % base_type.size) != 0:
    base_type = BASE_TYPE_BYTE
```

I don't really understand why though. Reading the spec, it looks like the Base Type Bit Field contains the base type number in the first 4 bits, but fitparse reads a whole byte and treats it as the base_type_num.

...

**Comment by pR0Ps** [comment]
64b7d2613 should fix this. Please reopen if this is not the case
