### ISSUE TITLE
I just want to rewrite a corrected Garmin fit file

### ISSUE THREAD

**Issue by btiller** [dtcooper/python-fitparse#115]
Thanks for fitparse!  I was able to use python to read my messed up garmin files and correct them (especially the heart rate data when my watch messes up).  But all I want to do is rewrite that same binary datafile back out with the corrected field data.  I read that you are not supporting a generic fit file writer and i understand that.  but is there something already out there that I can use to just reproduce what I read in with fitfile but it just has a modified field in it?  
Thanks!

**Comment by dlenski** [comment]
Why not use https://github.com/Tigge/FIT-to-TCX/ to write the output in TCX format?

TCX can convey all (nearly all?) of the same data as FIT, but in a more human-readable and -editable format.

**Comment by dtcooper** [comment]
Yeah, the library doesn't support writing. Sorry!
