### ISSUE TITLE
add a setup.py file to master branch

### ISSUE THREAD

**Issue by petergardfjall** [dtcooper/python-fitparse#12]
Until the ng branch has matured (it seems unstable at the moment, as I cannot parse my FIT files), I would like to use the master branch of the project (preferably using pip/distutils to install the module from github). I guess that the same, or a very similar, setup.py file that is used on the ng branch could be used, so the effort involved should be minimal.

**Comment by petergardfjall** [comment]
David, have you gotten around to look at this?

**Comment by dtcooper** [comment]
Not yet! Thanks for the reminder.

**Comment by pR0Ps** [comment]
Fixed as of 1cc59e64fe76ec26c6a588037a6e9a0678af714a
