### ISSUE TITLE
import fitparse fails with "SyntaxError: multiple exception types must be parenthesized"

### ISSUE THREAD

**Issue by CentralHarlemAnonymous** [dtcooper/python-fitparse#144]
The offending line seems to be "    except Exception, e:"

**Comment by pR0Ps** [comment]
The only instance of this I can find is in the API docs, which I have fixed in #145 . These docs aren't run in any way on import so no idea why you would be seeing an error from it. Is the `SyntaxError` in code that you copied from the docs? Or maybe it's from a different library? I'd need to see a traceback to look any more into it.

**Comment by CentralHarlemAnonymous** [comment]
Traceback (most recent call last):

  File ~/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3553 in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  Cell In[52], line 1
    import fitparse

  File ~/Library/Mobile Documents/com~apple~CloudDocs/Documents/programming/python/fitparse/fitparse/__init__.py:1
    from fitparse.activity import Activity

  File ~/Library/Mobile Documents/com~apple~CloudDocs/Documents/programming/python/fitparse/fitparse/activity.py:2
    from fitparse.base import FitFile

  File ~/Library/Mobile Documents/com~apple~CloudDocs/Documents/programming/python/fitparse/fitparse/base.py:72
    except Exception, e:
           ^
SyntaxError: multiple exception types must be parenthesized

**Comment by pR0Ps** [comment]
I think you may have the wrong library. The traceback mentions the module `fitparse.activity` which doesn't exist.

Also, not sure if it's a copy/paste error but the line `from fitparse.activity import Activity File` that's mentioned in the traceback is already a syntax error (needs a `,` between the things to import) so not sure what's happening there.
