### ISSUE TITLE
FitFile Parse error on Activity File with Developer data

### ISSUE THREAD

**Issue by sanderroosendaal** [dtcooper/python-fitparse#21]
r = FitFile('C:/Downloads/1484672807-GIR.fit')

r.parse()

FitParseErrorTraceback (most recent call last)
<ipython-input-8-377150abc632> in <module>()
----> 1 r.parse()

C:\Users\e408191\AppData\Local\Continuum\Anaconda2\lib\site-packages\fitparse\base.pyc in parse(self)
    424 
    425     def parse(self):
--> 426         while self._parse_message():
    427             pass
    428 

C:\Users\e408191\AppData\Local\Continuum\Anaconda2\lib\site-packages\fitparse\base.pyc in _parse_message(self)
    130             message = self._parse_definition_message(header)
    131         else:
--> 132             message = self._parse_data_message(header)
    133 
    134         self._messages.append(message)

C:\Users\e408191\AppData\Local\Continuum\Anaconda2\lib\site-packages\fitparse\base.pyc in _parse_data_message(self, header)
    265         if not def_mesg:
    266             raise FitParseError('Got data message with invalid local message type %d' % (
--> 267                 header.local_mesg_num))
    268 
    269         raw_values = self._parse_raw_values_from_data_message(def_mesg)

FitParseError: Got data message with invalid local message type 4

[1484672807-GIR.zip](https://github.com/dtcooper/python-fitparse/files/908229/1484672807-GIR.zip)

**Comment by pR0Ps** [comment]
Fixed as of 1cc59e64fe76ec26c6a588037a6e9a0678af714a
