### ISSUE TITLE
compressed / plugin framework HR data with event_timestamps not in datetime

### ISSUE THREAD

**Issue by haualan** [dtcooper/python-fitparse#26]
Thanks for this awesome library first of all!  I just have some questions on this file that I couldn't seem to wrap my head around.

When I parse the HR data in the attached file I found some event_timestamps that are represented with a 32 bit integer:

[<FieldData: filtered_bpm: (91, 90, 90, 90, 90, 90, 90, 90) [bpm], def num: 6, type: uint8 (uint8), raw value: (91, 90, 90, 90, 90, 90, 90, 90)>,
 <FieldData: event_timestamp: 103767638410559546792952933162482 [s], def num: 9, type: uint32 (uint32), raw value: 103767638410559546792952933162482>,
 <FieldData: event_timestamp: 103770559888591208310651742719474 [s], def num: 9, type: uint32 (uint32), raw value: 103770559888591208310651742719474>,
 <FieldData: event_timestamp: 103773481366622869828350552276466 [s], def num: 9, type: uint32 (uint32), raw value: 103773481366622869828350552276466>,
 <FieldData: event_timestamp: 103776402844654531346049361833458 [s], def num: 9, type: uint32 (uint32), raw value: 103776402844654531346049361833458>,
 <FieldData: event_timestamp: 103779324322686192863748171390450 [s], def num: 9, type: uint32 (uint32), raw value: 103779324322686192863748171390450>,
 <FieldData: event_timestamp: 103782245800717854381446980947442 [s], def num: 9, type: uint32 (uint32), raw value: 103782245800717854381446980947442>,
 <FieldData: event_timestamp: 103785167278749515899145790504434 [s], def num: 9, type: uint32 (uint32), raw value: 103785167278749515899145790504434>,
 <FieldData: event_timestamp: 103788088756781177416844600061426 [s], def num: 9, type: uint32 (uint32), raw value: 103788088756781177416844600061426>,
 <FieldData: event_timestamp: 103791010234812838934543409618418 [s], def num: 9, type: uint32 (uint32), raw value: 103791010234812838934543409618418>,
 <FieldData: event_timestamp: 103793931712844500452242219175410 [s], def num: 9, type: uint32 (uint32), raw value: 103793931712844500452242219175410>,
 <FieldData: event_timestamp_12: (242, 125, 9, 151, 112, 9, 151, 112, 9, 151, 112, 9), def num: 10, type: byte (byte), raw value: (242, 125, 9, 151, 112, 9, 151, 112, 9, 151, 112, 9)>]

Any ideas on how I can convert this back to a ISO Date time / unix timestamp / datetime object.

[pluginHR.zip](https://github.com/dtcooper/python-fitparse/files/1085526/pluginHR.zip)

**Comment by pR0Ps** [comment]
Did some testing - this only happens in Python 2. Python 3 parses it correctly.

**Comment by pR0Ps** [comment]
@haualan can you confirm that [the fix I pushed](https://github.com/dtcooper/python-fitparse/issues/28) works for you on other files as well? Also, I added the file you attached to the repo as part of the test suite. If you would rather I didn't (personal information in it?), I can take it out, just let me know.

**Comment by haualan** [comment]
thanks @pR0Ps the file can be included in the test suite.

The seconds integer didn't quite match up with the entire length of the activity. I think there is some quirk in the integer conversion.

if you see the p.42 of the FIT SDK in attached, the event_timestamp_12 has 12 integers in them but when expanded into event_timestamps there should only be 8 of them.

The current fix shows 12 of them. Any ideas?


[D00001275 Flexible & Interoperable Data Transfer (FIT) Protocol Rev 2.3.pdf](https://github.com/dtcooper/python-fitparse/files/1087238/D00001275.Flexible.Interoperable.Data.Transfer.FIT.Protocol.Rev.2.3.pdf)

**Comment by pR0Ps** [comment]
Reopening for further investigation

**Comment by pR0Ps** [comment]
After going through the FIT SDK, I think what's there is correct. Here is a section from `FitSDKRelease_20.35.00/cpp/fit_profile.cpp`:

Note there are 10 `event_timestamp` components.

```c++
static const Profile::FIELD_COMPONENT hrEventTimestamp12Components[] =
{
   { (FIT_FLOAT64)1024, (FIT_FLOAT64)0, 9, 12, FIT_TRUE }, // event_timestamp
   { (FIT_FLOAT64)1024, (FIT_FLOAT64)0, 9, 12, FIT_TRUE }, // event_timestamp
   { (FIT_FLOAT64)1024, (FIT_FLOAT64)0, 9, 12, FIT_TRUE }, // event_timestamp
   { (FIT_FLOAT64)1024, (FIT_FLOAT64)0, 9, 12, FIT_TRUE }, // event_timestamp
   { (FIT_FLOAT64)1024, (FIT_FLOAT64)0, 9, 12, FIT_TRUE }, // event_timestamp
   { (FIT_FLOAT64)1024, (FIT_FLOAT64)0, 9, 12, FIT_TRUE }, // event_timestamp
   { (FIT_FLOAT64)1024, (FIT_FLOAT64)0, 9, 12, FIT_TRUE }, // event_timestamp
   { (FIT_FLOAT64)1024, (FIT_FLOAT64)0, 9, 12, FIT_TRUE }, // event_timestamp
   { (FIT_FLOAT64)1024, (FIT_FLOAT64)0, 9, 12, FIT_TRUE }, // event_timestamp
   { (FIT_FLOAT64)1024, (FIT_FLOAT64)0, 9, 12, FIT_TRUE }, // event_timestamp
};

static const Profile::FIELD hrFields[] = {
{ 0, 0, "timestamp", "", (FIT_FLOAT64)1, (FIT_FLOAT64)0, 0, 0, 253, 134, false, Profile::Type::DateTime },
{ 0, 0, "fractional_timestamp", "s", (FIT_FLOAT64)32768, (FIT_FLOAT64)0, 0, 0, 0, 132, false, Profile::Type::Uint16 },
{ hrTime256Components, 0, "time256", "s", (FIT_FLOAT64)256, (FIT_FLOAT64)0, 1, 0, 1, 2, false, Profile::Type::Uint8 },
{ 0, 0, "filtered_bpm", "bpm", (FIT_FLOAT64)1, (FIT_FLOAT64)0, 0, 0, 6, 2, false, Profile::Type::Uint8 },
{ 0, 0, "event_timestamp", "s", (FIT_FLOAT64)1024, (FIT_FLOAT64)0, 0, 0, 9, 134, true, Profile::Type::Uint32 },
{ hrEventTimestamp12Components, 0, "event_timestamp_12", "", (FIT_FLOAT64)1, (FIT_FLOAT64)0, 10, 0, 10, 13, false, Profile::Type::Byte },
};
```

`Profile::Field` is defined in `FitSDKRelease_20.35.00/cpp/fit_profile.hpp` as:
```c++
typedef struct
{
    const FIELD_COMPONENT* components;
    const SUBFIELD* subFields;
    std::string name;
    std::string units;
    FIT_FLOAT64 scale;
    FIT_FLOAT64 offset;
    FIT_UINT16 numComponents;
    FIT_UINT16 numSubFields;
    FIT_UINT8 num;
    FIT_UINT8 type;
    FIT_BOOL isAccumulated;
    Type profileType;
} FIELD;
```
Note that the variable named`numComponents` in this structs maps to the parameter `10` for the `event_timestamp_12` field above.

All this pretty definitively points to at least the number of `event_timestamp` fields being correct.

The values being parsed out look reasonable to me. Would you be able to somehow get known correct values for the last message in the file? Please re-open this issue and post your results if you end up getting something different that what is currently being output.
