### ISSUE TITLE
Fails parse of `developer_data_id` record without `application_id`

### ISSUE THREAD

**Issue by Tigge** [dtcooper/python-fitparse#35]
When trying to parse a fit file I'm running into trouble. This is what I get back running `fitdump` on master:

```
Traceback (most recent call last):
  File "./scripts/fitdump", line 92, in <module>
    main()
  File "./scripts/fitdump", line 86, in main
    for n, message in enumerate(messages, 1):
  File "/media/BigHDD/Home stuff/Dropbox/Dropbox/Personal/Programming/python-fitparse/fitparse/base.py", line 450, in get_messages
    message = self._parse_message()
  File "/media/BigHDD/Home stuff/Dropbox/Dropbox/Personal/Programming/python-fitparse/fitparse/base.py", line 163, in _parse_message
    add_dev_data_id(message)
  File "/media/BigHDD/Home stuff/Dropbox/Dropbox/Personal/Programming/python-fitparse/fitparse/records.py", line 367, in add_dev_data_id
    application_id = message.get('application_id').raw_value
AttributeError: 'NoneType' object has no attribute 'raw_value'
```

I believe this is due to fitparse trying to read a nonexisting field in a `developer_data_id` record. This file has only the `developer_data_index` and not `application_id` which fitparse seems to always want to read.

**Comment by Tigge** [comment]
Thank you! Just out of curiosity (I'm not familiar with the code) - are you
are not fetching which blocks to read from the definition records in this
case or is this done automatically in some other place of the code?

**Comment by pR0Ps** [comment]
Disclaimer: I'm not the original developer (that would be @dtcooper) or the person who wrote the developer extensions code (@nall) so I'm not the best person to be answering this but I'll give it a shot.

When parsing messages, if the type name is `developer_data_id`, a dev type is recorded with the data index (`developer_data_index`) and application id (`application_id`). If the type name is `field_description`, the data index is used to look up the existing dev type and define the fields of that type. The data is the automatically parsed using those fields in the same way as all the other predefined fields in the spec.

Does that answer your question?
