### ISSUE TITLE
Corrdinates units?

### ISSUE THREAD

**Issue by F3L1X79** [dtcooper/python-fitparse#43]
Sorry to bother you guys, but in my .fit file the output of fitparse for _laps_ and _records_ are like:
```
"start_position_lat": 299017398,
"start_position_long": 1451139338,
```
What kind of unit is this?
 For information, desired output is:
```
"start_position_lat" : 25.06334876641631,
"start_position_long":: 121.6330941952765,
```
I get them for another file, they should be the same - but I'm currently unable to do the conversion between each other.
Any help is greatly appreciated.

**Comment by sanderroosendaal** [comment]
latitude = fit_latitude*(180./2**31)

The units in .fit are semicircles
