### ISSUE TITLE
Question: extracting duration

### ISSUE THREAD

**Issue by gamb** [dtcooper/python-fitparse#49]
Hi, thanks for this useful library. Just having a play with some of the usage examples. Appreciate anyone who could tell me if this is a reliable way to calculate duration (and if there isn't an easier way)...

```python
import fitparse

ff = fitparse.FitFile('…')

records = list(ff.get_messages(name='record'))

start_time = None
end_time = None

for record in records:
    timestamp = record.get_value('timestamp')
    if not start_time:
        start_time = timestamp
    end_time = timestamp

print("Started:", start_time)
print("Duration:", end_time - start_time)
```

I'm assuming:

- `list(ff.get_messages(name='record'))` will always be in chronological order
- there isn't a 'duration' field I could pull out instead

Can anyone confirm this?

**Comment by jeanbaptistemora** [comment]
Hello,

You can get_messages with "name" == "session". These are the different sports/activities selected on the device.
Inside those, in most of the fit files I've seen (40k+ so far) you have a field named "total_elapsed_time" (and in most cases also "total_time_time" depending on what you want).

So simply do :
`
sessions = list(fit.get_messages(name='session'))
duration = sum([session.get_value('total_elapsed_time') for session in sessions])
`

Enjoy :)

**Comment by gamb** [comment]
Awesome @jeanbaptistemora :)
