### ISSUE TITLE
Change Bitcoin donation address?

### ISSUE THREAD

**Issue by pR0Ps** [dtcooper/python-fitparse#53]
Might want to rethink one starting with `1GAYJEW`.

To be clear, I have no issue at all with adding a donation address and personally I couldn't care less what it says. However, in my opinion it's just not very professional. Plus, the internet hate machine can be vindictive, no matter the reason. Seems safer to just generate a new one and sidestep the whole issue.

**Comment by dtcooper** [comment]
Seems wise. I'll revert. :)
