### ISSUE TITLE
FIT File with RunScribe Plus

### ISSUE THREAD

**Issue by mattschultheis** [dtcooper/python-fitparse#62]
I recently purchased a RunScribe Plus, which adds running dynamics (but not Garmin Running Dynamics) data to the the .fit file via a ConnectIQ data field (example file here: [file](https://drive.google.com/open?id=1CruSthjf33NjEr0SfRzbOCg1sQg-yvqX) )

I am no longer able parse the file using fitparse. I get the following error 

`~\AppData\Local\Continuum\anaconda3\envs\pfda\lib\site-packages\fitparse\records.py in __iter__(self)
    152     def __iter__(self):
    153         # Sort by whether this is a known field, then its name
--> 154         return iter(sorted(self.fields, key=lambda fd: (int(fd.field is None), fd.name)))
    155 
    156     def __repr__(self):

TypeError: '<' not supported between instances of 'NoneType' and 'str'`

when trying to run this code:

`for record in fitfile.get_messages('record'):
    for record_data in record:
        pass`

Any ideas?

**Comment by xmedeko** [comment]
Seems like it contains a message with no field. May you put your FIT somewhere do download or at least provide a full stack trace?

**Comment by mattschultheis** [comment]
Sorry - I'm new to using fitparse, currently running from a Jupyter notebook.

Cropped part of file that I'm trying to parse:
[https://drive.google.com/open?id=1CruSthjf33NjEr0SfRzbOCg1sQg-yvqX](https://drive.google.com/open?id=1CruSthjf33NjEr0SfRzbOCg1sQg-yvqX)

Entire error trace:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-972e94e6ac20> in <module>()
      5 
      6 for record in fitfile.get_messages('record'):
----> 7     for record_data in record:
      8         pass
      9 

~\AppData\Local\Continuum\anaconda3\envs\pfda\lib\site-packages\fitparse\records.py in __iter__(self)
    152     def __iter__(self):
    153         # Sort by whether this is a known field, then its name
--> 154         return iter(sorted(self.fields, key=lambda fd: (int(fd.field is None), fd.name)))
    155 
    156     def __repr__(self):

TypeError: '<' not supported between instances of 'NoneType' and 'str'

**Comment by xmedeko** [comment]
I've found three bugs when parsing this file by `fitdump`:
- Some fields has no name for a message `#36` (record).
- The `StandardUnitsDataProcessor` fails when speed is a tuple, see again message `#36`.
- `enhanced` fields are twice in a record, when the record, e.g. message `#36` has twice `enhanced_altitude`, twice `enhanced_speed`.  It's because it's included there first time from a `ComponentField`, second time as a field itself.
