### ISSUE TITLE
FitParseError invalid field size 227 for type 'sint32'

### ISSUE THREAD

**Issue by sanderroosendaal** [dtcooper/python-fitparse#64]
After upgrading fitparse to the latest (master branch), one of my standard test files fails to parse. This is a file produced by a NK SpeedCoach GPS 2 device. The file parses well on SportTracks, Strava, etc. 

C:\Users\e408191\AppData\Local\Continuum\Anaconda2\lib\site-packages\fitparse\base.pyc in _parse_definition_message(self, header)
    196                 # examples in the wild. For now, just throw an exception
    197                 raise FitParseError("Invalid field size %d for type '%s' (expected a multiple of %d)" % (
--> 198                     field_size, base_type.name, base_type.size))
    199 
    200             # If the field has components that are accumulators

FitParseError: Invalid field size 227 for type 'sint32' (expected a multiple of 4)

[3x250m.zip](https://github.com/dtcooper/python-fitparse/files/1937064/3x250m.zip)

**Comment by sanderroosendaal** [comment]
My last successful build was 12 days ago

**Comment by xmedeko** [comment]
I've tried `scripts\fitdump 3x250m.fit` and it has processed without any error. What version of Python do you use? How to you use fitparse (e.g. do you use fitdump or your own python code?).

**Comment by sanderroosendaal** [comment]
Here is some example code that gives the error:
`from fitparse import FitFile
f = '../testdata/3x250m.fit
fitfile = FitFile(f,check_crc=False)
fitfile.parse()`

**Comment by xmedeko** [comment]
What exact version returns `python --version` ?

**Comment by sanderroosendaal** [comment]
Not sure I understand your comment (probably my fault) but on Travis-CI it fails as well. https://travis-ci.org/sanderroosendaal/rowingdata/builds/369964083

**Comment by pR0Ps** [comment]
Sure, remove the shim.

As a sidenote, In the future I would prefer it if commits could go into a
PR before they hit master.
