### ISSUE TITLE
Smart Mode Logic

### ISSUE THREAD

**Issue by woodmicha** [dtcooper/python-fitparse#67]
I have one more question (not an issue) as we've been unable to establish the exact logic Garmin uses for smart recording mode. I'm curious if you know how it works or have any documents that detail it?

We have a function to expand a stream that has been recorded with smart mode on. Right now we propagate values back in time instead of pulling the last value forward.

For example:

time[0] = 1; watts[0] = 100
time[1] = 2; watts[1] = 110
time[2] = 4; watts[2] = 115

yields [push back]:

watts[0] = 110
watts[1] = 110
watts[2] = 115
watts[3] = 115

instead of [pull forward]:
watts[0] = 110
watts[1] = 110
watts[2] = 110
watts[3] = 115

Do you know which approach is proper?

Thanks in advance for any pointers.

**Comment by xmedeko** [comment]
From a [DC Rainmaker comment](https://www.dcrainmaker.com/2016/03/configure-watches-datafields.html#comment-1481833) I think it's none from above:

1 sec recording: 130bpm, 131bpm, 133bpm, 135bpm, 135bpm, 137bpm
Smart Recording might be: 130bpm, 137bpm

I have not seen any document from Garmin about FIT file semantics and how they do record workouts. I guess they keep it secret. It's always blackbox reverse engineering, unfortunately.

**Comment by dukeduck1984** [comment]
I think it's always sampled at 1Hz when power data is presenting?  I simply use interpolation to get the second-by-second info from smart recorded data.
