### ISSUE TITLE
Problem on timestamp extraction

### ISSUE THREAD

**Issue by hugokernel** [dtcooper/python-fitparse#69]
Hi,

I work on a tool to extract data from Swimming Strap HRM from fit files and when I try to display data as chart, I see big difference between real chart (from Garmin Connect) and data extracted from fit-parse.

After investigation, I found a difference in the fitparse timestamp calculation compared to same data extracted from the Garmin FitCSVTool.

First 4 lines of Strap HRM data extracted with Garmin FitCSVTool (format: filtered_bpm, event_timestamp) :

```
71|71|71|71|71|71|71|71,2224910.171875|2224911.158203125|2224912.220703125|2224913.0419921875|2224913.7802734375|2224914.5126953125|2224915.34765625|2224915.7939453125
71|71|71|71|71|71|71|71,2224916.271484375|2224916.982421875|2224917.2734375|2224919.5859375|2224920.556640625|2224921.078125|2224921.45703125|2224921.990234375
71|71|72|72|72|73|73|74,2224924.7451171875|2224925.24609375|2224925.7421875|2224926.2412109375|2224927.1728515625|2224927.73828125|2224928.2197265625|2224928.6328125
74|74|75|77|83|84|87|89,2224929.126953125|2224929.619140625|2224930.1142578125|2224930.62890625|2224931.1552734375|2224931.67578125|2224932.1982421875|2224932.72265625
```

I use this code to extract and format data :

```
from fitparse import FitFile
fitfile = FitFile('lagny_fim.fit')
for _, msg in enumerate(fitfile.get_messages('hr')):

    if msg.header.local_mesg_num == 12:
        startat = round(msg.get('event_timestamp').value)
        continue

    timestamps = []
    for field in msg.fields:
        if field.name == 'event_timestamp':
            timestamps.append(startat + float(field.value))

    print('%s,%s' % (
        '|'.join(str(bpm) for bpm in msg.get('filtered_bpm').value),
        '|'.join(str(t) for t in timestamps)
    ))
```
Data extracted with this script  :

```
71|71|71|71|71|71|71|71,2224912.17188|2224913.1582|2224914.2207|2224915.04199|2224915.78027|2224916.5127|2224917.34766|2224917.79395|2224918.0|2224918.0                                                                        
71|71|71|71|71|71|71|71,2224918.27148|2224918.98242|2224919.27344|2224921.58594|2224922.55664|2224923.07812|2224923.45703|2224923.99023|2224926.0|2224926.0                                                                     
71|71|72|72|72|73|73|74,2224926.74512|2224927.24609|2224927.74219|2224928.24121|2224929.17285|2224929.73828|2224930.21973|2224930.63281|2224934.0|2224934.0                                                                     
74|74|75|77|83|84|87|89,2224935.12695|2224935.61914|2224936.11426|2224936.62891|2224937.15527|2224937.67578|2224938.19824|2224938.72266|2224942.0|2224942.0   
```

As you ca see, there are an error of +2 seconds on calculated timestamp and maybe other errors that occur in the extraction that would explain the overall errors in extracting heart rate data.

Do you have an idea of what can happen?
Am I making a mistake in extracting data?

I can provide the original fit file for investigation.

Thank you.

**Comment by polyvertex** [comment]
Same issue here with an HRM-Tri strap.

I stumbled upon a working example after some head scratching:

```python
    from fitparse import FitFile
    fitfile = FitFile('lagny_fim.fit')
    for _, msg in enumerate(fitfile.get_messages('hr')):

        if msg.header.local_mesg_num == 12:
            startat = msg.get('event_timestamp').raw_value
            continue

        timestamps = []
        for field in msg.fields:
            if field.name == 'event_timestamp':
                if len(timestamps) < len(msg.get('event_timestamp_12').raw_value) * 8 / 12:
                    timestamps.append(
                        (startat & 0xfffff000) / 1024 + float(field.value))

        print('%s,%s' % (
            '|'.join(str(bpm) for bpm in msg.get('filtered_bpm').value),
            '|'.join(str(t) for t in timestamps)
        ))
```

There *seem* to be 2 issues here:

* While fitparse parses the records correctly, it does not handle `event_timestamp_12` properly. Since I'm not familiar enough with the whole protocol nor with fitparse, I'm not sure whether this field and its logic should be considered a special case or if fitparse's code in handling field components should be revised.

* Also, I'm not sure why Fit SDK's `Profiles.xlsx` would list **10** `event_timestamp` components for field `event_timestamp_12` (`hr` message), whereas it can only hold **8** of them. Leading then fitparse to blindly output 10 `event_timestamp` fields. Not sure there is a mistake in `Profiles.xlsx` or in the way it is interpreted, for the lack of proper FIT specifications.

**Comment by hugokernel** [comment]
I will try that as soon as possible.
Thx

**Comment by pdura** [comment]
Hi polyvertex,
Thanks a lot for your feedback on this as I was also wondering how to get hr from my swim strap.
I'm still missing something there. How do you convert the timestamp you've got from this code to a real epoch timestamp ? I know the fit parser does it well but I can't manage to find where :/
I'm trying to add the UTC_REFERENCE but I still don't have a valid one.
Thanks a lot for your help there.

**Comment by polyvertex** [comment]
Hey @pdura, `hr` messages are appended to the file during the post-activity synchronization stage. E.g. on Garmin devices, it's when you `Save` your activity. Then it is up to your file reader to apply the content of these late `hr` messages to the `record` messages you previously read.

Regarding the timestamps, fitparse, makes them available to you. `fitdump` is invaluable for this kind of questions...
