### ISSUE TITLE
Installing from pip produces error message

### ISSUE THREAD

**Issue by anthonyjchriste** [dtcooper/python-fitparse#78]
Trying to install python-fitparse from pip produces the following error:

> pip install python-fitparse
> Collecting python-fitparse
>   Could not find a version that satisfies the requirement python-fitparse (from versions: )
> No matching distribution found for python-fitparse
> 

Python: 3.7.0
pip: 18.1
OS: OS X 10.13.4

**Comment by anthonyjchriste** [comment]
Sorry, I just realized the package name is fitparse, not python-fitparse. FYI, the documentation at http://dtcooper.github.io/python-fitparse/ is out of date. If I find some time I will clean it up and submit a pull request.

**Comment by dtcooper** [comment]
Yay! Thank you. Pull requests always welcome, especially ones cleaning up + adding docs :)
