### ISSUE TITLE
Exception in add_dev_field_description at line 395

### ISSUE THREAD

**Issue by woodmicha** [dtcooper/python-fitparse#83]
Recently started to see an exception when parsing FIT files.  I believe it may be related to them originating from a wahoo element device.

The error is a key error for the BASE_TYPES dict.  The key is 143 which in hex is 0x8F.  Some of the other variables include:

<DataMessage: field_description (#206) -- local mesg: #0, fields: [developer_data_index: 3, field_definition_number: 0, fit_base_type_id: uint64, field_name: time_ms, units: ms]>  

My guess is this is related to 64bit data types coming in the messages.  

Can this be solved by updating the profile to a later SDK? 

Thanks for any guidance...

**Comment by dtcooper** [comment]
This is actually fixed, @woodmicha. See [theses lines of code](https://github.com/dtcooper/python-fitparse/blob/79803587/fitparse/records.py#L428-L430). Please install from latest master.

**Comment by woodmicha** [comment]
Thanks for the quick reply and solution!
